apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ca.org1.example.com
  name: ca.org1.example.com
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: ca.org1.example.com
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ca.org1.example.com
    spec:
      containers:
      - command:
        - sh
        - -c
        - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
          --ca.keyfile /etc/hyperledger/fabric-ca-server-config/19ab65abbb04807dad12e4c0a9aaa6649e70868e3abd0217a322d89e47e1a6ae_sk
          -b admin:adminpw -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca.org1.example.com
        image: hyperledger/fabric-ca:x86_64-1.0.0
        imagePullPolicy: ""
        name: ca.org1.example.com
        ports:
        - containerPort: 7054
        resources: {}
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server-config
          name: .crypto-configpeerOrganizationsorg1.example.comca
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: ./crypto-config/peerOrganizations/org1.example.com/ca/
        name: .crypto-configpeerOrganizationsorg1.example.comca
status:
  replicas: 0
