apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: couchdb
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 5984
    protocol: ""
    targetPort: 0
  selector:
    service: couchdb
status:
  loadBalancer: {}
