apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: peer0.org1.example.com
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 7051
    protocol: ""
    targetPort: 0
  - name: ""
    nodePort: 0
    port: 7053
    protocol: ""
    targetPort: 0
  selector:
    service: peer0.org1.example.com
status:
  loadBalancer: {}
