apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: peer0.org1.example.com
  name: peer0.org1.example.com
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: peer0.org1.example.com
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: peer0.org1.example.com
    spec:
      containers:
      - command:
        - peer
        - node
        - start
        - --peer-defaultchain=false
        env:
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_ID
          value: peer0.org1.example.com
        - name: CORE_PEER_ADDRESS
          value: peer0.org1.example.com:7051
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: composer_default
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/peer/msp
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: couchdb:5984
        image: hyperledger/fabric-peer:x86_64-1.0.0
        imagePullPolicy: ""
        name: peer0.org1.example.com
        ports:
        - containerPort: 7051
        - containerPort: 7053
        resources: {}
        volumeMounts:
        - mountPath: /host/var/run/
          name: varrun
        - mountPath: /etc/hyperledger/configtx
          name: .
        - mountPath: /etc/hyperledger/peer/msp
          name: .crypto-configpeerOrganizationsorg1.example.compeerspeer0.org1.example.commsp
        - mountPath: /etc/hyperledger/msp/users
          name: .crypto-configpeerOrganizationsorg1.example.comusers
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /var/run/
        name: varrun
      - hostPath:
          path: ./
        name: .
      - hostPath:
          path: ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
        name: .crypto-configpeerOrganizationsorg1.example.compeerspeer0.org1.example.commsp
      - hostPath:
          path: ./crypto-config/peerOrganizations/org1.example.com/users
        name: .crypto-configpeerOrganizationsorg1.example.comusers
status:
  replicas: 0
